### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by guidol** [browneyedsoul/RemNote-ModernTableRow#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

it doesn't work in my Remnote.
Could you please explain about prerequisite.
i just copy..and past
Then put the Table number next to the title. using ' ## ' 

what i am missing??

![image](https://user-images.githubusercontent.com/19164042/205494969-fb15df1b-10b5-4d01-b143-e69e7e9d2593.png)

**Comment by browneyedsoul** [comment]
Hey, Thanks for reaching! First of all, I need to check your several states.
These things might be problems
1. Please check whether the plugin has installed or not
2. CSS priority conflict (Please test it in another Knowledge Base - plain new KB)

It seems that you may have changed a lot with CSSs with `!important` sort of forced rules
Can you please check the upper lists?

Thanks

**Comment by guidol** [comment]
Hey MK,

1. I installed the plugin
2. how i do the test in my Remnote? could you please give me more details?
3. I already did, but could make it. :(
4. I asked to Remnote support, but they also did not understand the description in plugin. 


Best Regards,
Cho

**Comment by browneyedsoul** [comment]
I might find what your problem was.

Can you check your Tag name? It shouldn't be wrapped in ` `

**Comment by browneyedsoul** [comment]
2. You can turn off other CSSs in your KB. Could you please test it with all the other CSSs being turned off?

**Comment by guidol** [comment]
![image](https://user-images.githubusercontent.com/19164042/205499818-df4e4a15-48e8-40d9-9510-508b64df9729.png)
this one??

You can turn off other CSSs in your KB. Could you please test it with all the other CSSs being turned off? --> I don't know how? could you give me a guidance?

**Comment by browneyedsoul** [comment]
In Custom CSS Page,

![221205-003629](https://user-images.githubusercontent.com/56161102/205500011-32f1b641-0005-43d6-afdd-bdb1cde22d81.png)

**Comment by guidol** [comment]
i have only 
![image](https://user-images.githubusercontent.com/19164042/205500955-72cafa1e-5113-4799-8289-f6c9fa109866.png)

and this one

![image](https://user-images.githubusercontent.com/19164042/205500974-494459ae-d7e2-4c32-b2de-e02b2fed9c5f.png)

and those status are "unchecked"

**Comment by browneyedsoul** [comment]
Could you provide RemNote version and Browser/Desktop are you using?

Sorry for inconvinence ;)

**Comment by guidol** [comment]
Version 1.8.55
Windows 10 /64bit

**Comment by browneyedsoul** [comment]
Then, what about broswer? Chrome / Edge / Firefox / Desktop App / Others
