### ISSUE TITLE
The plugin keeps uninstalling

### ISSUE THREAD

**Issue by thediagonalley** [browneyedsoul/RemNote-ModernTableRow#7]
After a couple of days the plugin just uninstalls, and I have to re install it every time. I don't know if its got something to do with my app or is it the plugin?

**Comment by browneyedsoul** [comment]
That seems like a very unusual case. Do all the other plugins behave the same way?

**Comment by thediagonalley** [comment]
Just this one

**Comment by browneyedsoul** [comment]
Did you ever reach out to the team about this issue through the lower right question mark button?

**Comment by thediagonalley** [comment]
I didn't, but since then the plugin has been running smoothly, hasn't uninstalled again or anything. Thank you for answering!

**Comment by browneyedsoul** [comment]
That's good news!
