### ISSUE TITLE
Extreme slowdown

### ISSUE THREAD

**Issue by faldor20** [browneyedsoul/RemNote-ModernTableRow#9]
With this plugin enabled the interface for remnote becomes extremely unresponsive. I'm talking seconds just to make a new rem, all pages take a noticeable time to load. etc
Disabling the plugin immediately fixed the issue.

PS: love the plugin look and feel, super useful

**Comment by browneyedsoul** [comment]
Thanks for feedback :)
Can you provide me the specification of your computer?

Best,

**Comment by browneyedsoul** [comment]
I realized that the huge size of the CSS is causing a problem. I need to rebuild the entire SCSS code, but I currently don't have much time to do that. Nevertheless, I will address this issue as soon as possible.

Thanks!
